# Generated by Django 3.0.8 on 2020-12-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hf_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('component_uid', models.UUIDField(primary_key=True, serialize=False)),
                ('component_id', models.IntegerField()),
                ('component_name', models.TextField(blank=True, null=True)),
                ('component_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'components',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentsTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'components_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemsCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_uid', models.UUIDField()),
                ('item_desc', models.TextField(blank=True, null=True)),
                ('upd_date', models.DateTimeField()),
                ('item_type_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'items_catalog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemTranslations',
            fields=[
                ('item_uid', models.UUIDField(primary_key=True, serialize=False)),
                ('language_code', models.TextField()),
                ('translation', models.TextField(blank=True, null=True)),
                ('table_source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemTypesCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type_uid', models.UUIDField()),
                ('item_type_desc', models.TextField(blank=True, null=True)),
                ('upd_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'item_types_catalog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('language_id', models.IntegerField()),
                ('language_code', models.TextField(primary_key=True, serialize=False)),
                ('language_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeasureUnits',
            fields=[
                ('measure_unit_uid', models.UUIDField(primary_key=True, serialize=False)),
                ('measure_unit_id', models.IntegerField()),
                ('measure_unit_name', models.TextField(blank=True, null=True)),
                ('measure_unit_src_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'measure_units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeasureUnitsTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'measure_units_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductComponents',
            fields=[
                ('rec_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_desc', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_components',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_proirity', models.IntegerField(blank=True, null=True)),
                ('image_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_uid', models.UUIDField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('product_name', models.TextField(blank=True, null=True)),
                ('product_src_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('tag_name', models.TextField(blank=True, null=True)),
                ('tag_type', models.TextField(blank=True, null=True)),
                ('rec_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecepiInstructionTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recepi_instruction_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecepiTags',
            fields=[
                ('rec_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_name', models.TextField(blank=True, null=True)),
                ('tag_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recepi_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecepiTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recepi_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelationUserMeal',
            fields=[
                ('id_relation', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_relation', models.TextField()),
            ],
            options={
                'db_table': 'relation_user_meal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_uid', models.UUIDField(primary_key=True, serialize=False)),
                ('tag_name', models.TextField(blank=True, null=True)),
                ('tag_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TagsCategory',
            fields=[
                ('id_tag_category', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.TextField()),
            ],
            options={
                'db_table': 'tags_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TagsTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tags_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersMealAdditionals',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('id_meal', models.IntegerField()),
            ],
            options={
                'db_table': 'users_meal_additionals',
                'managed': False,
            },
        ),
    ]
