# Generated by Django 3.0.8 on 2020-12-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hf_website', '0002_components_componentstranslations_itemscatalog_itemtranslations_itemtypescatalog_languages_measureun'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersFoodLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_weight', models.IntegerField()),
                ('food_time', models.TextField()),
                ('date_creation', models.DateField()),
            ],
            options={
                'db_table': 'users_food_log',
                'managed': False,
            },
        ),
    ]
